layout_spectrum: 0.7210408165119588
typography_spectrum: 0.5488347916398197
color:
  brandStrength: 0.5694581815041602
  lightness: 0.47886759461835027
  saturation: 0.12105000182054937
  rhythmicContrast: 0.6267232000827789
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
author:
  name: Darren Cornwell
  email: darren@irregularactivity.co.uk
  url: irregularactivity.co.uk
name: safe
title: The burden of belief
description: What goes upwards... must continue onwards.
