layout_spectrum: 0.2943442231044173
typography_spectrum: 0.08364933030679822
color:
  brandStrength: 0.2667185871396214
  lightness: 0.7749994779005647
  saturation: 0.2133184028789401
  rhythmicContrast: 0.3344362748321146
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
author:
  name: Darren Cornwell
  email: darren@irregularactivity.co.uk
  url: irregularactivity.co.uk
name: safe
title: The burden of belief
description: What goes upwards... must continue onwards.
